### ISSUE TITLE
Screencasts link

### ISSUE THREAD

**Issue by MattOates** [perl6/perl6.org#39]
Might be worth getting the two maintained YouTube video lists somewhere in the screencasts section.

https://www.youtube.com/playlist?list=PLRuESFRW2Fa77XObvk7-BYVFwobZHdXdK for English and other languages https://www.youtube.com/playlist?list=PLRuESFRW2Fa6PBxZ8oQhKqV8zZak3bHNN

**Comment by jotasprout** [comment]
Can I take this? Asking to prevent redundant/wasted work on anyone's part.

**Comment by coke** [comment]
Please do!

**Comment by jotasprout** [comment]
Awesome-sauce. Been looking in vain for "the screenscasts section." Help a brother out?

**Comment by jotasprout** [comment]
The link to Perl 6 screencasts under For Newcomers on Per 6 Documentation opens an external site/page so I'm assuming it isn't a file in the repo --  should I:
1. Add a Screencasts header on Documentation 
2. Add a subheader, "szabgab screencasts" with links to each from that site under it
3. Remove "Perl 6 screencasts" from For Newcomers
4. Add subheaders for English and Other Language under the new Screencasts header and list/link to those respective videos?

**Comment by zoffixznet** [comment]
> 1. Add a Screencasts header on Documentation 
2. Add a subheader, "szabgab screencasts" with links to each from that site under it
3. Remove "Perl 6 screencasts" from For Newcomers
4. Add subheaders for English and Other Language under the new Screencasts header and list/link to those respective videos?

1. Yes, add a separate panel for it
2. That can be just description of the link and not necessarily a subheader
3. Yes.
4. Again, can be part of the description of the link, rather than a subheader.

**Comment by jotasprout** [comment]
There are 121 English vids (including the seven that are also on the szasgab site). Y'all want all of them listed?

**Comment by zoffixznet** [comment]
I think including just the links to the playlists is sufficient.

**Comment by jotasprout** [comment]
Dagnabbit (he says after making oodles of individual links). Okay, one short list coming up.

**Comment by zoffixznet** [comment]
This has been resolved by https://github.com/perl6/perl6.org/pull/58
